@API_HostAddress = http://localhost:5192

GET {{API_HostAddress}}/weatherforecast/
Accept: application/json

###Data Source=kkplanner.database.windows.net,1433;Initial Catalog=kkplanner;User ID=kristo;Password=poisike
